### ISSUE TITLE
free : the handle is invalid

### ISSUE THREAD

**Issue by npenin** [tjfontaine/node-vlc#4]
Hi,

In the media.js file, it tries to do the following (which does not work on my computer win8-x64). Isn't is linux specific, of isn't there a way of disposing the media directly within the libvlc api ?

``` javascript
var libc = ffi.Library(null, {
  'free': ['void', [ 'pointer' ]],
});
```

**Comment by skiqh** [comment]
Same error message for me on win7-x86.

```
d:\vlc\node_modules\vlc\node_modules\ffi\lib\dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
          ^
Error: Dynamic Symbol Retrieval Error: "free": The handle is invalid.
    at DynamicLibrary.get (d:\vlc\node_modules\vlc\node_modules\ffi\lib\dynamic_library.js:112:11)
    at d:\vlc\node_modules\vlc\node_modules\ffi\lib\library.js:50:19
    at Array.forEach (native)
    at Object.Library (d:\vlc\node_modules\vlc\node_modules\ffi\lib\library.js:47:28)
    at Object.<anonymous> (d:\vlc\node_modules\vlc\lib\media.js:28:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

libvlc.dll is in `C:\Program Files\VideoLAN\VLC` (version 2.1.2)

**Comment by xdenser** [comment]
Workaround for Windows.

``` javascript
var libc = ffi.Library('msvcrt', {
  'free': ['void', [ 'pointer' ]],
});
```
